### PR TITLE
Fix #256: Run Script: do not launch new blender window when blender is busy

### LINKED ISSUE #256: Blender starts unexpected when restarting halted script
Steps to Reproduce: 

1. Start Blender 
2. Run a Script 
3. Halt the script with a breakpoint 
4. Forget that your script is halted and try to start it again 

Behaviour: 
* Suddenly a wild Blender appears in front of you and desperately tries to run your script 

Expected behaviour: 
* Nothing 
* Eventually a note: "Would you like to terminate your debugging session and rerun the script?" 

Version: 0.0.29 
Last known Working Version 0.0.26 (0.0.27 ... maybe, but in my case Blender hasn't been alive long enough to test it) 

Image

Blender 4.2.1 LTS

### PR DESCRIPTION
**Pull request by Mateusz-Grzelinski**
#256 

This patch depends on the fact that cleanup (and `kill`) seems to work ok

please fix typo in commit message when merging

### CODE REVIEW

File: src/commands_scripts.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export async function COMMAND_runScript(args?: RunScriptCommandArguments): Promi
         throw new Error('script path could not be determined');
     }
 
-    const instances = await RunningBlenders.getResponsive();
+    const instances = RunningBlenders.getAllive();
```
Comment (JacquesLucke) [inline src/commands_scripts.ts]: typo (`alive`), multiple times below, also in a comment

File: src/communication.ts [hunk 2]
```diff
@@ -101,6 +101,9 @@ export class RunningBlenderInstances {
         this.instances = this.instances.filter(item => item.vscodeIdentifier !== vscodeIdentifier);
     }
 
+    /** Blender with allive and responsive web server is considered running.
+     * Note: not response might be caused by CPU usage or active breakpoint in debugger
```
Comment (JacquesLucke) [inline src/communication.ts]: typo (`not` -> `no`)

File: src/communication.ts [hunk 3]
```diff
@@ -110,6 +113,13 @@ export class RunningBlenderInstances {
         return this.instances.filter((_, index) => responsiveness[index]);
     }
 
+    /** There is no direct way to check if process is allive.
+     * The correctness is guranteed by correct cleanup in kill method.
```
Comment (JacquesLucke) [inline src/communication.ts]: typo (`guaranteed`)
